version: '3.1'                                  
                                                
services:                                       
  container1:                                         
    container_name: container1                        
    build:                                      
      context: .                                
      dockerfile: Dockerfile                    
    image: container1                                  
    network_mode: "host"                        
    environment:                                
      TZ: "Europe/London"                       
    volumes:                                    
      - /Users/azib/Downloads/test:/host_shared 
