name: auto_exo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.13
  - astropy
  - astroquery
  - black
  - bokeh==2.2.3
  - celerite
  - cython
  - jupyterlab
  - mamba
  - matplotlib
  - numexpr
  - numba==0.53.0
  - numpy
  - pandas
  - plotly
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow
  - tk
  - tqdm
  - pickle5
  - pip
  - pip:
    - lightkurve>=2
    - eleanor
    - kplr
    - markupsafe==2.0.1
    - wotan
