name: exocomet2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - astropy
  - astroquery
  - black
  - bokeh==2.2.3
  - cython
  - jupyterlab
  - matplotlib
  - numexpr
  - numba
  - numpy
  - pandas
  - plotly
  - scikit-learn
  - scipy
  - seaborn
  - tensorflow
  - tk
  - tqdm
  - pip
  - pylint
  - umap-learn
  - pip:
    - lightkurve>=2
    - eleanor
    - markupsafe>=2.1.1
    - wotan
